# Generated by Django 5.2.4 on 2025-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='worst_answer',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user_answer',
            field=models.CharField(blank=True, null=True),
        ),
    ]
